
package com.utils.webservice.demo;

import org.springframework.stereotype.Component;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HBJ_smsCenterPortType", targetNamespace = "http://controller.sms.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HBJSmsCenterPortType {


    /**
     * 
     * @param wsurl
     * @param mesNO
     * @param system
     * @param method
     * @param phones
     * @param content
     * @param officeNO
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:go")
    @WebResult(targetNamespace = "http://controller.sms.com")
    @RequestWrapper(localName = "go", targetNamespace = "http://controller.sms.com", className = "cn.ljl.sand.jws.chapter3.client.wsimport.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://controller.sms.com", className = "cn.ljl.sand.jws.chapter3.client.wsimport.GoResponse")
    public String go(
            @WebParam(name = "phones", targetNamespace = "http://controller.sms.com")
                    String phones,
            @WebParam(name = "content", targetNamespace = "http://controller.sms.com")
                    String content,
            @WebParam(name = "officeNO", targetNamespace = "http://controller.sms.com")
                    String officeNO,
            @WebParam(name = "mesNO", targetNamespace = "http://controller.sms.com")
                    String mesNO,
            @WebParam(name = "wsurl", targetNamespace = "http://controller.sms.com")
                    String wsurl,
            @WebParam(name = "method", targetNamespace = "http://controller.sms.com")
                    String method,
            @WebParam(name = "system", targetNamespace = "http://controller.sms.com")
                    String system);

}
