
package com.utils.webservice.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HBJ_smsCenter", targetNamespace = "http://controller.sms.com", wsdlLocation = "http://10.12.100.133:8080/hbj_sms_ws/services/HBJ_smsCenter?wsdl")
public class HBJSmsCenter
    extends Service
{

    private final static URL HBJSMSCENTER_WSDL_LOCATION;
    private final static WebServiceException HBJSMSCENTER_EXCEPTION;
    private final static QName HBJSMSCENTER_QNAME = new QName("http://controller.sms.com", "HBJ_smsCenter");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.12.100.133:8080/hbj_sms_ws/services/HBJ_smsCenter?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HBJSMSCENTER_WSDL_LOCATION = url;
        HBJSMSCENTER_EXCEPTION = e;
    }

    public HBJSmsCenter() {
        super(__getWsdlLocation(), HBJSMSCENTER_QNAME);
    }

    public HBJSmsCenter(WebServiceFeature... features) {
        super(__getWsdlLocation(), HBJSMSCENTER_QNAME, features);
    }

    public HBJSmsCenter(URL wsdlLocation) {
        super(wsdlLocation, HBJSMSCENTER_QNAME);
    }

    public HBJSmsCenter(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HBJSMSCENTER_QNAME, features);
    }

    public HBJSmsCenter(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HBJSmsCenter(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HBJSmsCenterPortType
     */
    @WebEndpoint(name = "HBJ_smsCenterHttpSoap11Endpoint")
    public HBJSmsCenterPortType getHBJSmsCenterHttpSoap11Endpoint() {
        return super.getPort(new QName("http://controller.sms.com", "HBJ_smsCenterHttpSoap11Endpoint"), HBJSmsCenterPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HBJSmsCenterPortType
     */
    @WebEndpoint(name = "HBJ_smsCenterHttpSoap11Endpoint")
    public HBJSmsCenterPortType getHBJSmsCenterHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.sms.com", "HBJ_smsCenterHttpSoap11Endpoint"), HBJSmsCenterPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HBJSMSCENTER_EXCEPTION!= null) {
            throw HBJSMSCENTER_EXCEPTION;
        }
        return HBJSMSCENTER_WSDL_LOCATION;
    }

}
