server:
  port: 8000
  tomcat:
    max-connections: 2000  #（最大连接数）
    max-threads: 100 #（最大线程数）
    accept-count: 80 # （最大等待数）

#配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log

#DFS 连接配置
connect_timeout: 2
network_timeout: 30
charSet: UTF-8
tracker_server: 192.168.154.128:22122
http:
  tracker_http_port: 8888
  anti_steal_token: no
  secret_key: FastDFS1234567890

scheduledStr: 0 */1 * * * ? #获取token定时器时间设置

